import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import ContactCardComponent from "@/components/contact-card";
import PricingComponent from "@/components/pricing";
import { Button } from "@aws-amplify/ui-react";
import { METHODS } from "http";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  async function openAI() {
    console.log("before API call");
    const res = await fetch("http://localhost:3000/api/hello", {
      method: "POST",
    });
    const data = await res.json();
    console.log("after API call");
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.grid}>
          <Link href="/auth">
            <h2 className={inter.className}>
              Auth <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Auth features are here</p>
          </Link>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              GraphQL API <span>-&gt;</span>
            </h2>
            <p className={inter.className}>GraphQL API Features are here</p>
          </a>
          <Link href="/storage">
            <h2 className={inter.className}>
              Storage <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Storage features are here</p>
          </Link>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Analytics <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Analytics features are here</p>
          </a>
        </div>
        <div>
          <ContactCardComponent
            name="John Doe"
            email="johndoe@example.com"
            image="/vercel.svg"
          />
        </div>
        <div>
          <PricingComponent />
          <Button onClick={openAI}>testing ChatGPT</Button>
        </div>
      </main>
    </>
  );
}
